apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stuurwiel
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - nats.yaml
  - rabbitmq.yaml
  - kafka.yaml
  - api.yaml
  - worker-nats-kafka.yaml
  - worker-kafka-rabbit.yaml
  - worker-rabbit-nats.yaml
