// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/grpc/stuurwiel/v1/stuurwiel.proto

package stuurwielv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target broker: "nats", "kafka", or "rabbitmq".
	Broker        string `protobuf:"bytes,1,opt,name=broker,proto3" json:"broker,omitempty"`
	EventId       int64  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Text          string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_api_grpc_stuurwiel_v1_stuurwiel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_stuurwiel_v1_stuurwiel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *PublishRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *PublishRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Broker        string                 `protobuf:"bytes,1,opt,name=broker,proto3" json:"broker,omitempty"`
	BytesWritten  int32                  `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_api_grpc_stuurwiel_v1_stuurwiel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_stuurwiel_v1_stuurwiel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *PublishResponse) GetBytesWritten() int32 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

var File_api_grpc_stuurwiel_v1_stuurwiel_proto protoreflect.FileDescriptor

const file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDesc = "" +
	"\n" +
	"%api/grpc/stuurwiel/v1/stuurwiel.proto\x12\fstuurwiel.v1\"W\n" +
	"\x0ePublishRequest\x12\x16\n" +
	"\x06broker\x18\x01 \x01(\tR\x06broker\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"N\n" +
	"\x0fPublishResponse\x12\x16\n" +
	"\x06broker\x18\x01 \x01(\tR\x06broker\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x05R\fbytesWritten2X\n" +
	"\x0eMessageService\x12F\n" +
	"\aPublish\x12\x1c.stuurwiel.v1.PublishRequest\x1a\x1d.stuurwiel.v1.PublishResponseB-Z+stuurwiel/api/grpc/stuurwiel/v1;stuurwielv1b\x06proto3"

var (
	file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDescOnce sync.Once
	file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDescData []byte
)

func file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDescGZIP() []byte {
	file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDescOnce.Do(func() {
		file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDesc), len(file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDesc)))
	})
	return file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDescData
}

var file_api_grpc_stuurwiel_v1_stuurwiel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_grpc_stuurwiel_v1_stuurwiel_proto_goTypes = []any{
	(*PublishRequest)(nil),  // 0: stuurwiel.v1.PublishRequest
	(*PublishResponse)(nil), // 1: stuurwiel.v1.PublishResponse
}
var file_api_grpc_stuurwiel_v1_stuurwiel_proto_depIdxs = []int32{
	0, // 0: stuurwiel.v1.MessageService.Publish:input_type -> stuurwiel.v1.PublishRequest
	1, // 1: stuurwiel.v1.MessageService.Publish:output_type -> stuurwiel.v1.PublishResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_stuurwiel_v1_stuurwiel_proto_init() }
func file_api_grpc_stuurwiel_v1_stuurwiel_proto_init() {
	if File_api_grpc_stuurwiel_v1_stuurwiel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDesc), len(file_api_grpc_stuurwiel_v1_stuurwiel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_stuurwiel_v1_stuurwiel_proto_goTypes,
		DependencyIndexes: file_api_grpc_stuurwiel_v1_stuurwiel_proto_depIdxs,
		MessageInfos:      file_api_grpc_stuurwiel_v1_stuurwiel_proto_msgTypes,
	}.Build()
	File_api_grpc_stuurwiel_v1_stuurwiel_proto = out.File
	file_api_grpc_stuurwiel_v1_stuurwiel_proto_goTypes = nil
	file_api_grpc_stuurwiel_v1_stuurwiel_proto_depIdxs = nil
}
